name: Automate Repository

on:
  push:
    paths:
      - "en.json"
      - "contributors.json"
      - "*.ts"
  workflow_dispatch:

jobs:
  auto:
    runs-on: ubuntu-latest
    name: "Automate Repository"

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Bottomify translations
        run: deno run --allow-read --allow-write bottomify.ts
      - name: Convert to enchantment table
        run: deno run --allow-read --allow-write enchantment.ts
      - name: Convert to leet code
        run: deno run --allow-read --allow-write leet.ts
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.json"
          message: "chore: update automatic languages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README
        run: deno run --allow-read --allow-write calculate.ts
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "*.md"
          message: "chore: re-generate README"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
